// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8zTQNbIy-kF4IMmCUojKNxHZtgw-jBQ',
    appId: '1:697908495744:web:c31fb67c1a751b2819ed65',
    messagingSenderId: '697908495744',
    projectId: 'bucketlistwithfirebase-f1558',
    authDomain: 'bucketlistwithfirebase-f1558.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-f1558.firebasestorage.app',
    measurementId: 'G-9FBTMN6JYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4Dn6mazv1ec4OkjcpC9mNT_S1uVJPaI',
    appId: '1:697908495744:android:39b40ae0f4552f5c19ed65',
    messagingSenderId: '697908495744',
    projectId: 'bucketlistwithfirebase-f1558',
    storageBucket: 'bucketlistwithfirebase-f1558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHJU02eGEKNklPFRpLOzQG4VpM1Enoqs',
    appId: '1:697908495744:ios:04dad5d592d6c06219ed65',
    messagingSenderId: '697908495744',
    projectId: 'bucketlistwithfirebase-f1558',
    storageBucket: 'bucketlistwithfirebase-f1558.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARHJU02eGEKNklPFRpLOzQG4VpM1Enoqs',
    appId: '1:697908495744:ios:04dad5d592d6c06219ed65',
    messagingSenderId: '697908495744',
    projectId: 'bucketlistwithfirebase-f1558',
    storageBucket: 'bucketlistwithfirebase-f1558.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw8zTQNbIy-kF4IMmCUojKNxHZtgw-jBQ',
    appId: '1:697908495744:web:a0e0707c39907d1419ed65',
    messagingSenderId: '697908495744',
    projectId: 'bucketlistwithfirebase-f1558',
    authDomain: 'bucketlistwithfirebase-f1558.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-f1558.firebasestorage.app',
    measurementId: 'G-VVRV495LGX',
  );

}